import { acronymGlossary } from '@/lib/acronyms';

export type GlossarySourceType = 'legal-dictionary' | 'regulatory-guidance' | 'assurance-standard' | 'internal';

export type GlossaryEntry = {
  term: string;
  definition: string;
  plainEnglishDefinition?: string;
  aliases?: string[];
  sourceType?: GlossarySourceType;
  sourceAuthority?: string;
  sourceUrl?: string;
  frameworkTags?: string[];
  wizardStages?: string[];
  trustScaffoldInterpretation?: string;
};

const domainDefinitions: GlossaryEntry[] = [
  {
    term: 'Approved document',
    definition: 'A generated document version that has passed review and is marked as export-eligible.',
    sourceType: 'internal',
    sourceAuthority: 'TrustScaffold Product Semantics',
    frameworkTags: ['SOC2'],
    wizardStages: ['Review', 'Generate'],
  },
  {
    term: 'Archived document',
    definition: 'A document version moved out of active review/export workflows.',
    sourceType: 'internal',
    sourceAuthority: 'TrustScaffold Product Semantics',
    frameworkTags: ['SOC2'],
    wizardStages: ['Review', 'Generate'],
  },
  {
    term: 'Carve-out',
    definition: 'An audit reporting model where certain controls are excluded from your report and covered by a vendor report.',
    plainEnglishDefinition: 'You rely on another company\'s controls for part of your system and reference their report.',
    sourceType: 'assurance-standard',
    sourceAuthority: 'AICPA SOC Reporting Concepts',
    sourceUrl: 'https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2',
    frameworkTags: ['SOC2'],
    wizardStages: ['Infrastructure'],
  },
  {
    term: 'Control environment',
    definition: 'The overall set of governance, security, and operational controls that shape compliance posture.',
    plainEnglishDefinition: 'The tone, structure, and accountability model that determines whether controls are real in practice.',
    sourceType: 'assurance-standard',
    sourceAuthority: 'COSO Internal Control Framework',
    sourceUrl: 'https://www.coso.org/internal-control',
    frameworkTags: ['SOC2', 'COSO'],
    wizardStages: ['Governance', 'Security Assessment'],
  },
  {
    term: 'Decision trace',
    definition: 'A rule-driven explanation of why warnings, recommendations, or deep-dive questions were shown in the wizard.',
    sourceType: 'internal',
    sourceAuthority: 'TrustScaffold Rule Engine',
    frameworkTags: ['SOC2', 'NIST-CSF'],
    wizardStages: ['Review'],
  },
  {
    term: 'Draft document',
    definition: 'A generated policy artifact pending reviewer decision (approve, reject, or archive).',
    sourceType: 'internal',
    sourceAuthority: 'TrustScaffold Product Semantics',
    frameworkTags: ['SOC2'],
    wizardStages: ['Generate'],
  },
  {
    term: 'Evidence artifact',
    definition: 'A collected technical or procedural record used to support control operation during audit review.',
    plainEnglishDefinition: 'A saved record that proves a control was configured, executed, or reviewed.',
    sourceType: 'assurance-standard',
    sourceAuthority: 'AICPA Trust Services Criteria (Evidence Expectations)',
    sourceUrl: 'https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2',
    frameworkTags: ['SOC2', 'ISO27001', 'HIPAA', 'PCI'],
    wizardStages: ['Security Assessment', 'Security Tooling', 'Generate'],
  },
  {
    term: 'Inclusive',
    definition: 'An audit reporting model where applicable controls are tested directly in your report scope.',
    sourceType: 'assurance-standard',
    sourceAuthority: 'AICPA SOC Reporting Concepts',
    sourceUrl: 'https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2',
    frameworkTags: ['SOC2'],
    wizardStages: ['Infrastructure'],
  },
  {
    term: 'Subservice organization',
    definition: 'A third-party provider your system relies on for infrastructure or control operations.',
    plainEnglishDefinition: 'A vendor that operates part of the services your controls depend on.',
    sourceType: 'assurance-standard',
    sourceAuthority: 'AICPA SOC 2 Glossary Concepts',
    sourceUrl: 'https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2',
    frameworkTags: ['SOC2'],
    wizardStages: ['Infrastructure', 'Operations'],
  },
  {
    term: 'System Description',
    definition: 'A formal narrative defining what your system does, its boundaries, and related control context for the audit.',
    sourceType: 'assurance-standard',
    sourceAuthority: 'AICPA Description Criteria (DC 200)',
    sourceUrl: 'https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2',
    frameworkTags: ['SOC2'],
    wizardStages: ['System Scope', 'Review'],
  },
  {
    term: 'Template payload',
    definition: 'Structured wizard data passed into document templates during generation and regeneration.',
    sourceType: 'internal',
    sourceAuthority: 'TrustScaffold Template Engine',
    frameworkTags: ['SOC2', 'ISO27001', 'HIPAA', 'PCI'],
    wizardStages: ['Generate'],
  },
  {
    term: 'Wizard draft',
    definition: 'The saved in-progress organization profile and control answers captured in the policy wizard.',
    sourceType: 'internal',
    sourceAuthority: 'TrustScaffold Wizard Persistence Model',
    frameworkTags: ['SOC2'],
    wizardStages: ['Welcome', 'Infrastructure', 'System Scope', 'Governance', 'TSC Selection', 'Security Assessment', 'Security Tooling', 'Operations', 'Review'],
  },
  {
    term: 'Control',
    definition: 'A safeguard or process designed to reduce risk and meet a compliance objective.',
    plainEnglishDefinition: 'A repeatable way your team prevents or detects bad outcomes.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'NIST CSF 2.0 / NIST SP 800-53 Concepts',
    sourceUrl: 'https://www.nist.gov/cyberframework',
    frameworkTags: ['NIST-CSF', 'SOC2', 'ISO27001'],
    wizardStages: ['Governance', 'TSC Selection', 'Security Assessment', 'Security Tooling', 'Operations'],
    trustScaffoldInterpretation: 'Controls are expressed as policy language plus evidence expectations mapped to criteria.',
  },
  {
    term: 'Risk assessment',
    definition: 'A structured process for identifying threats, estimating impact and likelihood, and deciding treatment actions.',
    plainEnglishDefinition: 'A recurring decision process for what can go wrong and what you will do about it.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'NIST CSF Govern/Identify Functions; FFIEC CAT Concepts',
    sourceUrl: 'https://www.ffiec.gov/cyberassessmenttool.htm',
    frameworkTags: ['NIST-CSF', 'FFIEC', 'SOC2'],
    wizardStages: ['Governance', 'Security Assessment'],
  },
  {
    term: 'Material change',
    definition: 'A significant change in system, organization, vendor, or process that can alter control design or effectiveness.',
    plainEnglishDefinition: 'A change big enough that your current controls or documents may no longer be accurate.',
    sourceType: 'legal-dictionary',
    sourceAuthority: 'Cornell Legal Information Institute (materiality concept)',
    sourceUrl: 'https://www.law.cornell.edu/wex/materiality',
    frameworkTags: ['SOC2', 'SOX', 'ISO27001'],
    wizardStages: ['System Scope', 'Governance', 'Review'],
  },
  {
    term: 'Due diligence',
    definition: 'Reasonable and documented review performed before relying on a vendor, system, or claim.',
    plainEnglishDefinition: 'Checking and recording that a vendor or control can be trusted before you depend on it.',
    sourceType: 'legal-dictionary',
    sourceAuthority: 'Cornell Legal Information Institute',
    sourceUrl: 'https://www.law.cornell.edu/wex/due_diligence',
    frameworkTags: ['SOC2', 'ISO27001', 'FFIEC'],
    wizardStages: ['Infrastructure', 'Operations'],
  },
  {
    term: 'DSAR (Data Subject Access Request)',
    definition: 'A request from an individual to access, correct, or delete personal data held about them.',
    plainEnglishDefinition: 'A user asking what data you have and what you do with it, or asking to update/delete it.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'GDPR Articles 15-22 and CPRA rights concepts',
    sourceUrl: 'https://gdpr-info.eu/chapter-3/',
    frameworkTags: ['GDPR', 'CCPA', 'SOC2-Privacy'],
    wizardStages: ['Welcome', 'System Scope', 'Operations'],
  },
  {
    term: 'PHI (Protected Health Information)',
    definition: 'Individually identifiable health information protected under HIPAA.',
    plainEnglishDefinition: 'Health-related personal data that triggers HIPAA obligations.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: '45 CFR 160.103 (HIPAA definitions)',
    sourceUrl: 'https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-160/section-160.103',
    frameworkTags: ['HIPAA', 'SOC2'],
    wizardStages: ['System Scope', 'Review'],
  },
  {
    term: 'BAA (Business Associate Agreement)',
    definition: 'A contract required by HIPAA when a vendor or partner creates, receives, maintains, or transmits protected health information on behalf of a covered entity or business associate.',
    plainEnglishDefinition: 'The HIPAA contract that lets another company handle PHI under defined security and privacy obligations.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: '45 CFR 164.502(e) and 164.504(e)',
    sourceUrl: 'https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E',
    frameworkTags: ['HIPAA'],
    wizardStages: ['System Scope', 'Operations', 'Review'],
  },
  {
    term: 'HL7',
    definition: 'Health Level Seven is a family of healthcare data-exchange standards used to move clinical, administrative, and operational information between healthcare systems.',
    plainEnglishDefinition: 'A common standard hospitals, labs, payers, and healthcare software use to exchange patient and operational data.',
    aliases: ['H7', 'Health Level 7', 'Health Level Seven'],
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'HL7 International',
    sourceUrl: 'https://www.hl7.org/',
    frameworkTags: ['HIPAA', 'Healthcare'],
    wizardStages: ['System Scope'],
  },
  {
    term: 'FHIR',
    definition: 'Fast Healthcare Interoperability Resources is a modern HL7 standard for exchanging healthcare data through structured APIs and resource models.',
    plainEnglishDefinition: 'The newer healthcare API standard often used to move patient, encounter, and clinical data between apps and systems.',
    aliases: ['Fast Healthcare Interoperability Resources'],
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'HL7 FHIR specification',
    sourceUrl: 'https://www.hl7.org/fhir/overview.html',
    frameworkTags: ['HIPAA', 'Healthcare'],
    wizardStages: ['System Scope'],
  },
  {
    term: 'HL7 / FHIR',
    definition: 'Healthcare interoperability standards used to exchange clinical and patient data between systems.',
    plainEnglishDefinition: 'Common healthcare APIs and message formats for moving patient data between hospitals, apps, and platforms.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'HL7 International / FHIR specification',
    sourceUrl: 'https://www.hl7.org/fhir/overview.html',
    frameworkTags: ['HIPAA', 'Healthcare'],
    wizardStages: ['System Scope'],
  },
  {
    term: 'EDI',
    definition: 'Electronic Data Interchange is a structured standard for exchanging business and healthcare transaction data between organizations.',
    plainEnglishDefinition: 'A machine-readable file format often used for healthcare claims, remittance, eligibility, and partner data exchanges.',
    aliases: ['Electronic Data Interchange'],
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'ASC X12 / healthcare transaction concepts',
    sourceUrl: 'https://x12.org/',
    frameworkTags: ['HIPAA', 'Healthcare'],
    wizardStages: ['System Scope'],
  },
  {
    term: 'Minimum necessary',
    definition: 'A HIPAA principle requiring uses, disclosures, and access to PHI to be limited to the minimum reasonably necessary to accomplish the intended purpose.',
    plainEnglishDefinition: 'People should only see the health data they actually need for their job or task.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: '45 CFR 164.502(b)',
    sourceUrl: 'https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E/section-164.502',
    frameworkTags: ['HIPAA'],
    wizardStages: ['System Scope', 'Operations', 'Review'],
  },
  {
    term: 'CDE (Cardholder Data Environment)',
    definition: 'People, process, and technology components that store, process, or transmit cardholder data, or can impact its security.',
    plainEnglishDefinition: 'The systems and networks that touch payment card data directly or indirectly.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'PCI DSS Glossary',
    sourceUrl: 'https://www.pcisecuritystandards.org/document_library',
    frameworkTags: ['PCI-DSS', 'SOC2'],
    wizardStages: ['System Scope', 'Security Tooling', 'Review'],
  },
  {
    term: 'CHD (Cardholder Data)',
    definition: 'At minimum, the full primary account number (PAN), and potentially the cardholder name, expiration date, and service code when stored or processed together with the PAN.',
    plainEnglishDefinition: 'The payment-card details that PCI-DSS treats as protected data.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'PCI DSS Glossary',
    sourceUrl: 'https://www.pcisecuritystandards.org/document_library',
    frameworkTags: ['PCI-DSS'],
    wizardStages: ['System Scope', 'Review'],
  },
  {
    term: 'PCI SAQ (Self-Assessment Questionnaire)',
    definition: 'A PCI-DSS reporting form whose type depends on how a merchant or service provider handles payment-card data and payment flows.',
    plainEnglishDefinition: 'The PCI checklist version you complete based on your payment architecture.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'PCI Security Standards Council SAQ guidance',
    sourceUrl: 'https://www.pcisecuritystandards.org/document_library',
    frameworkTags: ['PCI-DSS'],
    wizardStages: ['System Scope', 'Review'],
  },
  {
    term: 'PCI merchant or service-provider level',
    definition: 'A PCI-DSS classification tier, typically Level 1 through Level 4, based on transaction volume and whether the organization acts as a merchant or service provider.',
    plainEnglishDefinition: 'Your PCI oversight tier, which affects validation rigor, assessor involvement, and reporting expectations.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'PCI SSC validation and merchant-level guidance',
    sourceUrl: 'https://www.pcisecuritystandards.org/document_library',
    frameworkTags: ['PCI-DSS'],
    wizardStages: ['System Scope', 'Review'],
  },
  {
    term: 'ASV (Approved Scanning Vendor)',
    definition: 'A scanning provider approved by the PCI Security Standards Council to perform required external vulnerability scans for PCI environments.',
    plainEnglishDefinition: 'The qualified vendor allowed to run PCI external scans against your payment environment.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'PCI ASV Program Guide',
    sourceUrl: 'https://www.pcisecuritystandards.org/program_training_and_qualification/approved_scanning_vendors',
    frameworkTags: ['PCI-DSS'],
    wizardStages: ['System Scope', 'Security Tooling', 'Review'],
  },
  {
    term: 'Tokenization',
    definition: 'A process that replaces sensitive payment-card data with a surrogate token that has no exploitable value outside the tokenization system.',
    plainEnglishDefinition: 'Swapping real card data for a safe placeholder so most systems never store raw card numbers.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'PCI tokenization guidance',
    sourceUrl: 'https://www.pcisecuritystandards.org/document_library',
    frameworkTags: ['PCI-DSS', 'SOC2'],
    wizardStages: ['System Scope', 'Review', 'Generate'],
  },
  {
    term: 'MFA (Multi-Factor Authentication)',
    definition: 'Authentication that requires at least two independent factors from different categories.',
    plainEnglishDefinition: 'Login protection that combines more than one proof, like password plus app code.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'NIST SP 800-63 Digital Identity Guidelines',
    sourceUrl: 'https://pages.nist.gov/800-63-3/',
    frameworkTags: ['NIST', 'SOC2', 'PCI'],
    wizardStages: ['Infrastructure', 'Operations', 'Security Tooling'],
  },
  {
    term: 'RTO (Recovery Time Objective)',
    definition: 'The target time to restore service after a disruption.',
    plainEnglishDefinition: 'How long you can be down before recovery must be complete.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'NIST SP 800-34 Contingency Planning',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-34/rev-1/final',
    frameworkTags: ['SOC2-Availability', 'ISO27001'],
    wizardStages: ['Security Assessment', 'Security Tooling', 'Review'],
  },
  {
    term: 'RPO (Recovery Point Objective)',
    definition: 'The maximum acceptable data loss measured in time.',
    plainEnglishDefinition: 'How much recent data you can afford to lose after an outage.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'NIST SP 800-34 Contingency Planning',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-34/rev-1/final',
    frameworkTags: ['SOC2-Availability', 'ISO27001'],
    wizardStages: ['Security Assessment', 'Security Tooling', 'Review'],
  },
  {
    term: 'SLA (Service Level Agreement)',
    definition: 'A documented commitment for service quality, availability, or response targets between provider and customer.',
    plainEnglishDefinition: 'A measurable promise about service performance or response times.',
    sourceType: 'legal-dictionary',
    sourceAuthority: 'Cornell LII (contract law concepts)',
    sourceUrl: 'https://www.law.cornell.edu/wex/contract',
    frameworkTags: ['SOC2', 'SOX'],
    wizardStages: ['Operations', 'Review'],
  },
  {
    term: 'SoD (Segregation of Duties)',
    definition: 'A control principle that separates sensitive responsibilities to reduce fraud and error risk.',
    plainEnglishDefinition: 'No single person should control every critical step of a high-risk process.',
    sourceType: 'assurance-standard',
    sourceAuthority: 'COSO / AICPA control design concepts',
    sourceUrl: 'https://www.coso.org/internal-control',
    frameworkTags: ['SOC2', 'SOX'],
    wizardStages: ['Governance', 'Operations', 'Review'],
  },
  {
    term: 'ICFR (Internal Control over Financial Reporting)',
    definition: 'Controls designed to provide reasonable assurance about the reliability of financial reporting and preparation of financial statements.',
    plainEnglishDefinition: 'The control system that makes financial reports dependable and reviewable.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'SEC/PCAOB SOX concepts',
    sourceUrl: 'https://www.sec.gov/rules/final/33-8238.htm',
    frameworkTags: ['SOX'],
    wizardStages: ['Welcome', 'Governance', 'Review'],
  },
  {
    term: 'Subprocessor',
    definition: 'A downstream vendor engaged by a processor to process personal data on behalf of a controller.',
    plainEnglishDefinition: 'A vendor used by your vendor to handle your customers\' data.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'GDPR processor/subprocessor model',
    sourceUrl: 'https://gdpr-info.eu/art-28-gdpr/',
    frameworkTags: ['GDPR', 'SOC2'],
    wizardStages: ['Infrastructure', 'Operations'],
  },
  {
    term: 'Risk register',
    definition: 'A maintained record of identified risks, owners, treatment plans, status, and review cadence.',
    plainEnglishDefinition: 'The working list of risks and what your team is doing about each one.',
    sourceType: 'regulatory-guidance',
    sourceAuthority: 'NIST risk management concepts; ISO 27001 risk treatment patterns',
    sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-30/rev-1/final',
    frameworkTags: ['NIST', 'ISO27001', 'SOC2', 'SOX'],
    wizardStages: ['Governance', 'Operations', 'Review'],
  },
];

const acronymEntries: GlossaryEntry[] = acronymGlossary.map((item) => ({
  term: item.shortForm,
  definition: item.longForm,
  sourceType: 'internal',
  sourceAuthority: 'TrustScaffold Acronym Glossary',
}));

function normalizedGlossaryKey(term: string): string {
  const acronymPrefixMatch = term.match(/^([A-Z0-9][A-Z0-9\s/-]{1,})\s*\([^)]*\)$/);
  if (acronymPrefixMatch) {
    return acronymPrefixMatch[1].trim().toLowerCase();
  }

  return term.trim().toLowerCase();
}

export const glossaryEntries: GlossaryEntry[] = Array.from(
  [...acronymEntries, ...domainDefinitions]
    .reduce<Map<string, GlossaryEntry>>((entries, entry) => {
      entries.set(normalizedGlossaryKey(entry.term), entry);
      return entries;
    }, new Map())
    .values()
).sort((a, b) => a.term.localeCompare(b.term, undefined, { sensitivity: 'base' }));
