import type { WizardData } from './schema';

export type TrustServiceScope = 'security' | 'availability' | 'confidentiality' | 'processingIntegrity' | 'privacy' | 'hipaa' | 'pci' | 'iso27001' | 'gdpr' | 'common';

export interface DocumentGenerationRule {
  slug: string;
  name: string;
  tsc: string;
  criteriaMapped: string[];
  criteriaHint: string;
  outputFilenamePattern: string;
  scope: TrustServiceScope;
  generationRequirement: string;
  wizardAnswerTrigger: string;
  description: string;
}

type DocumentRuleSelections = WizardData['tscSelections'] | WizardData;

function hasWizardContext(selections: DocumentRuleSelections): selections is WizardData {
  return 'scope' in selections && 'tscSelections' in selections;
}

export const documentGenerationRules: DocumentGenerationRule[] = [
  {
    slug: 'system-description',
    name: 'System Description (DC 200)',
    tsc: 'Security',
    criteriaMapped: ['CC1', 'CC2', 'CC3', 'CC4', 'CC5', 'CC6', 'CC7', 'CC8', 'CC9'],
    criteriaHint: 'All Security common criteria',
    outputFilenamePattern: '00-system-description.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because Security is mandatory and the system boundary must be documented for SOC 2 readiness.',
    wizardAnswerTrigger: 'tscSelections.security is always true; generation also requires company.name, scope.systemName, and scope.systemDescription to pass compile validation.',
    description: 'Auditor-facing narrative describing the in-scope system, system boundary, infrastructure, people, procedures, data, vendors, and control environment.',
  },
  {
    slug: 'information-security-policy',
    name: 'Information Security Policy',
    tsc: 'Security',
    criteriaMapped: ['CC1', 'CC2', 'CC5', 'CC6', 'CC7', 'CC8', 'CC9'],
    criteriaHint: 'CC1, CC2, CC5-CC9',
    outputFilenamePattern: '01-information-security-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because Security is mandatory and this is the master security governance policy.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Core policy establishing security objectives, ownership, environment summary, and organization-wide security expectations.',
  },
  {
    slug: 'access-control-on-offboarding-policy',
    name: 'Access Control and On/Offboarding Policy',
    tsc: 'Security',
    criteriaMapped: ['CC6'],
    criteriaHint: 'CC6',
    outputFilenamePattern: '02-access-control-on-offboarding-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because logical access, onboarding, offboarding, and privilege review are core Security requirements.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines provisioning, authentication, access reviews, offboarding, and access-request SOP expectations.',
  },
  {
    slug: 'incident-response-plan',
    name: 'Incident Response Plan',
    tsc: 'Security',
    criteriaMapped: ['CC7'],
    criteriaHint: 'CC7',
    outputFilenamePattern: '03-incident-response-plan.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because security event response is a core Security requirement.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines incident roles, triage, escalation, response lifecycle, post-incident review, and evidence expectations.',
  },
  {
    slug: 'change-management-policy',
    name: 'Change Management Policy',
    tsc: 'Security',
    criteriaMapped: ['CC8'],
    criteriaHint: 'CC8',
    outputFilenamePattern: '04-change-management-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because production change authorization and deployment control are core Security requirements.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines standard changes, emergency changes, segregation of duties, deployment guardrails, and production change SOP expectations.',
  },
  {
    slug: 'risk-management-policy',
    name: 'Risk Management Policy',
    tsc: 'Security',
    criteriaMapped: ['CC3', 'CC9'],
    criteriaHint: 'CC3, CC9',
    outputFilenamePattern: '05-risk-management-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because risk assessment and risk mitigation are core Security requirements.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines risk identification, scoring, treatment, review cadence, fraud-risk consideration, and remediation tracking.',
  },
  {
    slug: 'business-continuity-dr-plan',
    name: 'Business Continuity & Disaster Recovery Policy',
    tsc: 'Availability',
    criteriaMapped: ['A1'],
    criteriaHint: 'A1',
    outputFilenamePattern: '06-business-continuity-dr-plan.md',
    scope: 'availability',
    generationRequirement: 'Generate when Availability is selected because the organization has availability commitments, RTO/RPO expectations, recovery obligations, or customer dependency on system uptime.',
    wizardAnswerTrigger: 'tscSelections.availability is true.',
    description: 'Defines recovery objectives, continuity planning, dependency monitoring, recovery strategy, and DR evidence expectations.',
  },
  {
    slug: 'backup-recovery-policy',
    name: 'Backup & Recovery Policy',
    tsc: 'Availability',
    criteriaMapped: ['A1'],
    criteriaHint: 'A1',
    outputFilenamePattern: '07-backup-recovery-policy.md',
    scope: 'availability',
    generationRequirement: 'Generate when Availability is selected because backup execution, backup retention, and restore testing support availability commitments.',
    wizardAnswerTrigger: 'tscSelections.availability is true.',
    description: 'Defines backup frequency, backup retention, restore testing, recovery ownership, and provider-specific recovery expectations.',
  },
  {
    slug: 'data-classification-handling-policy',
    name: 'Data Classification & Handling Policy',
    tsc: 'Confidentiality',
    criteriaMapped: ['C1'],
    criteriaHint: 'C1',
    outputFilenamePattern: '08-data-classification-handling-policy.md',
    scope: 'confidentiality',
    generationRequirement: 'Generate when Confidentiality is selected because confidential information classification and handling must be documented.',
    wizardAnswerTrigger: 'tscSelections.confidentiality is true.',
    description: 'Defines classification tiers, handling requirements, approved systems, and confidentiality expectations for selected data types.',
  },
  {
    slug: 'encryption-policy',
    name: 'Encryption Policy',
    tsc: 'Confidentiality',
    criteriaMapped: ['C1'],
    criteriaHint: 'C1',
    outputFilenamePattern: '09-encryption-policy.md',
    scope: 'confidentiality',
    generationRequirement: 'Generate when Confidentiality is selected because encryption and key-management controls support confidentiality commitments.',
    wizardAnswerTrigger: 'tscSelections.confidentiality is true.',
    description: 'Defines encryption at rest, encryption in transit, cloud-provider controls, key management, and exception expectations.',
  },
  {
    slug: 'privacy-notice-consent-policy',
    name: 'Privacy Notice & Consent Framework',
    tsc: 'Privacy',
    criteriaMapped: ['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8'],
    criteriaHint: 'P1-P8',
    outputFilenamePattern: '10-privacy-notice-consent-policy.md',
    scope: 'privacy',
    generationRequirement: 'Generate when Privacy is selected. Customer PII or PHI answers should warn/recommend Privacy when omitted, but generation is controlled by the Privacy TSC selection.',
    wizardAnswerTrigger: 'tscSelections.privacy is true.',
    description: 'Defines privacy notice, consent, collection, use, retention, DSAR, disclosure, data-quality, complaint, and enforcement expectations.',
  },
  {
    slug: 'vendor-management-policy',
    name: 'Vendor Management Policy',
    tsc: 'Security',
    criteriaMapped: ['CC3', 'CC9'],
    criteriaHint: 'CC3, CC9',
    outputFilenamePattern: '11-vendor-management-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because vendor and subservice organization risk management is a core Security requirement, even when no vendors are listed.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines vendor due diligence, assurance report review, ongoing monitoring, subservice organizations, CSOCs, and vendor risk evidence.',
  },
  {
    slug: 'secure-sdlc-policy',
    name: 'Secure Software Development Life Cycle Policy',
    tsc: 'Security',
    criteriaMapped: ['CC8'],
    criteriaHint: 'CC8',
    outputFilenamePattern: '12-secure-sdlc-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because secure development, testing, and release control are core Security requirements.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines security requirements across design, development, review, testing, scanning, release, and remediation workflows.',
  },
  {
    slug: 'physical-security-policy',
    name: 'Physical Security Policy',
    tsc: 'Security',
    criteriaMapped: ['CC6'],
    criteriaHint: 'CC6',
    outputFilenamePattern: '13-physical-security-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because physical security responsibilities exist through office controls, inherited cloud data center controls, or self-hosted/hybrid assets.',
    wizardAnswerTrigger: 'tscSelections.security is always true. Infrastructure answers tailor the content but do not suppress this document.',
    description: 'Defines office, device, cloud data center inheritance, self-hosted, hybrid, media destruction, and physical-access evidence expectations.',
  },
  {
    slug: 'acceptable-use-code-of-conduct-policy',
    name: 'Acceptable Use and Code of Conduct Policy',
    tsc: 'Security',
    criteriaMapped: ['CC1', 'CC2'],
    criteriaHint: 'CC1, CC2',
    outputFilenamePattern: '14-acceptable-use-code-of-conduct-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because workforce conduct, acceptable use, and policy communication support Security common criteria.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines acceptable use, code of conduct, policy acknowledgement, approved software, device monitoring, reporting, and discipline expectations.',
  },
  {
    slug: 'evidence-checklist',
    name: 'SOC 2 Evidence Checklist',
    tsc: 'Security',
    criteriaMapped: ['CC1', 'CC2', 'CC3', 'CC4', 'CC5', 'CC6', 'CC7', 'CC8', 'CC9'],
    criteriaHint: 'Security criteria plus optional selected TSC evidence sections',
    outputFilenamePattern: '15-soc2-evidence-checklist.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because the evidence inventory is needed for readiness. Optional TSC answers add conditional evidence sections inside the document.',
    wizardAnswerTrigger: 'tscSelections.security is always true; optional sections render from tscSelections.availability, confidentiality, processingIntegrity, and privacy.',
    description: 'Lists evidence artifacts by control area and TSC criterion, including retention expectations and gaps driven by wizard answers.',
  },
  {
    slug: 'internal-audit-monitoring-policy',
    name: 'Internal Audit and Monitoring Policy',
    tsc: 'Security',
    criteriaMapped: ['CC2', 'CC4'],
    criteriaHint: 'CC2, CC4',
    outputFilenamePattern: '16-internal-audit-monitoring-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because controls monitoring, audit cadence, and deficiency remediation support Security common criteria.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines internal audit cadence, monitoring activities, deficiency remediation, reporting, and control-monitoring frequency requirements.',
  },
  {
    slug: 'data-retention-disposal-policy',
    name: 'Data Retention and Disposal Policy',
    tsc: 'Security',
    criteriaMapped: ['CC6', 'CC9'],
    criteriaHint: 'CC6, CC9',
    outputFilenamePattern: '17-data-retention-disposal-policy.md',
    scope: 'security',
    generationRequirement: 'Generate for every completed wizard because secure retention and disposal support Security access, asset handling, and risk mitigation expectations.',
    wizardAnswerTrigger: 'tscSelections.security is always true. Privacy and confidentiality answers tailor content but do not solely control this document.',
    description: 'Defines data inventory, retention schedule, deletion, disposal, subprocessor handling, and confidentiality agreement expectations.',
  },
  {
    slug: 'processing-integrity-policy',
    name: 'Processing Integrity Policy',
    tsc: 'Processing Integrity',
    criteriaMapped: ['PI1'],
    criteriaHint: 'PI1',
    outputFilenamePattern: '18-processing-integrity-policy.md',
    scope: 'processingIntegrity',
    generationRequirement: 'Generate when Processing Integrity is selected because complete, valid, accurate, timely, and authorized processing must be documented.',
    wizardAnswerTrigger: 'tscSelections.processingIntegrity is true.',
    description: 'Defines processing objectives, input validation, authorization, exception handling, reconciliation, output review, procedural annex, and evidence expectations.',
  },
  {
    slug: 'business-associate-agreement-template',
    name: 'Business Associate Agreement Template',
    tsc: 'HIPAA',
    criteriaMapped: ['HIPAA'],
    criteriaHint: 'HIPAA Security/Privacy Rule vendor contracting',
    outputFilenamePattern: '19-business-associate-agreement-template.md',
    scope: 'hipaa',
    generationRequirement: 'Generate when PHI is in scope because vendors handling PHI require Business Associate Agreement coverage before regulated healthcare data is shared.',
    wizardAnswerTrigger: 'scope.containsPhi is true.',
    description: 'Defines BAA terms, permitted PHI uses, safeguards, breach notification, subcontractor obligations, return/destruction, and audit evidence expectations.',
  },
  {
    slug: 'phi-data-flow-inventory-map',
    name: 'PHI Data Flow and Inventory Map',
    tsc: 'HIPAA',
    criteriaMapped: ['HIPAA'],
    criteriaHint: 'HIPAA PHI inventory and flow mapping',
    outputFilenamePattern: '20-phi-data-flow-inventory-map.md',
    scope: 'hipaa',
    generationRequirement: 'Generate when PHI is in scope because HIPAA readiness requires specific PHI systems, data elements, recipients, safeguards, and disclosure paths to be inventoried.',
    wizardAnswerTrigger: 'scope.containsPhi is true.',
    description: 'Captures PHI data elements, systems of record, flows, vendors, minimum-necessary access, retention, and evidence needed for HIPAA review.',
  },
  {
    slug: 'tokenization-cardholder-data-policy',
    name: 'Tokenization and Cardholder Data Policy',
    tsc: 'PCI-DSS',
    criteriaMapped: ['PCI'],
    criteriaHint: 'PCI-DSS cardholder data protection',
    outputFilenamePattern: '21-tokenization-cardholder-data-policy.md',
    scope: 'pci',
    generationRequirement: 'Generate when a cardholder data environment is in scope because PCI requires explicit CHD storage, masking, tokenization, transmission, and CDE boundary controls beyond generic encryption.',
    wizardAnswerTrigger: 'scope.hasCardholderDataEnvironment is true.',
    description: 'Defines CHD storage restrictions, tokenization, masking, SAD prohibition, key custody, CDE segmentation, and evidence requirements.',
  },
  {
    slug: 'quarterly-vulnerability-scanning-sop',
    name: 'Quarterly Vulnerability Scanning SOP',
    tsc: 'PCI-DSS',
    criteriaMapped: ['PCI'],
    criteriaHint: 'PCI-DSS ASV and quarterly scanning',
    outputFilenamePattern: '22-quarterly-vulnerability-scanning-sop.md',
    scope: 'pci',
    generationRequirement: 'Generate when a cardholder data environment is in scope because PCI requires quarterly external ASV scanning and vulnerability remediation evidence.',
    wizardAnswerTrigger: 'scope.hasCardholderDataEnvironment is true.',
    description: 'Defines quarterly ASV scans, internal scanning, rescans, remediation SLAs, scope confirmation, evidence retention, and exception handling.',
  },
  {
    slug: 'iso27001-statement-of-applicability',
    name: 'ISO 27001 Statement of Applicability',
    tsc: 'ISO 27001',
    criteriaMapped: ['ISO27001'],
    criteriaHint: 'ISO 27001 Annex A SoA',
    outputFilenamePattern: '23-iso27001-statement-of-applicability.md',
    scope: 'iso27001',
    generationRequirement: 'Generate for the baseline security package because the SoA is the ISO 27001 master index for selected, implemented, and excluded Annex A controls.',
    wizardAnswerTrigger: 'tscSelections.security is always true; ISO controls are included as the multi-framework high-water baseline.',
    description: 'Provides a starter Annex A applicability matrix with inclusion rationale, exclusion rationale, implementation status, owner, and linked TrustScaffold templates.',
  },
  {
    slug: 'legal-regulatory-registry',
    name: 'Legal and Regulatory Registry',
    tsc: 'ISO 27001',
    criteriaMapped: ['ISO27001', 'GDPR', 'CCPA', 'HIPAA', 'PCI'],
    criteriaHint: 'ISO 27001 legal obligations plus selected high-water frameworks',
    outputFilenamePattern: '24-legal-regulatory-registry.md',
    scope: 'iso27001',
    generationRequirement: 'Generate for the baseline security package because ISO 27001 expects legal, statutory, regulatory, and contractual obligations to be identified and reviewed.',
    wizardAnswerTrigger: 'tscSelections.security is always true; website, PHI, CDE, CCPA/CPRA, GDPR, and Privacy answers add framework-specific rows inside the registry.',
    description: 'Lists applicable laws, regulations, contractual commitments, owners, review cadence, evidence, and conditional HIPAA, PCI, GDPR, and privacy obligations.',
  },
  {
    slug: 'data-protection-impact-assessment',
    name: 'Data Protection Impact Assessment',
    tsc: 'GDPR / Privacy',
    criteriaMapped: ['GDPR', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8'],
    criteriaHint: 'GDPR DPIA and Privacy P1-P8',
    outputFilenamePattern: '25-data-protection-impact-assessment.md',
    scope: 'gdpr',
    generationRequirement: 'Generate when Privacy is selected or website answers indicate EU/UK personal-data or tracking exposure because high-risk personal-data processing may require a DPIA and related privacy risk analysis.',
    wizardAnswerTrigger: 'tscSelections.privacy is true, or websiteTargetsEuOrUkResidents / websiteUsesCookiesAnalytics indicate GDPR exposure.',
    description: 'Defines processing purpose, personal-data categories, lawful basis, necessity, proportionality, risks, mitigations, consultation, approval, and review expectations.',
  },
  {
    slug: 'asset-management-cryptographic-inventory',
    name: 'Asset Management and Cryptographic Inventory',
    tsc: 'Universal',
    criteriaMapped: ['COMMON', 'CC6', 'CC7', 'C1', 'ISO27001', 'PCI'],
    criteriaHint: 'Common control, ISO 27001, PCI, CC6, CC7, C1',
    outputFilenamePattern: '26-asset-management-cryptographic-inventory.md',
    scope: 'common',
    generationRequirement: 'Generate for every completed wizard because asset ownership, system inventory, cryptographic mechanisms, keys, certificates, and algorithms are common-control foundations across SOC 2, ISO 27001, PCI, HIPAA, and privacy programs.',
    wizardAnswerTrigger: 'tscSelections.security is always true.',
    description: 'Defines asset inventory, data stores, encryption algorithms, key custody, certificate inventory, rotation cadence, ownership, and evidence expectations.',
  },
];

export function isDocumentRuleSelected(rule: DocumentGenerationRule, selections: DocumentRuleSelections) {
  const tscSelections = hasWizardContext(selections) ? selections.tscSelections : selections;

  if (rule.scope === 'security' || rule.scope === 'common' || rule.scope === 'iso27001') return true;
  if (rule.scope === 'hipaa') return hasWizardContext(selections) ? selections.scope.containsPhi : false;
  if (rule.scope === 'pci') return hasWizardContext(selections) ? selections.scope.hasCardholderDataEnvironment : false;
  if (rule.scope === 'gdpr') {
    return tscSelections.privacy || (hasWizardContext(selections) && (selections.company.websiteTargetsEuOrUkResidents || selections.company.websiteUsesCookiesAnalytics));
  }

  return tscSelections[rule.scope];
}

export function getSelectedDocumentGenerationRules(selections: DocumentRuleSelections) {
  return documentGenerationRules.filter((rule) => isDocumentRuleSelected(rule, selections));
}
