import type { WizardData } from '@/lib/wizard/schema';

export function buildTemplatePayload(data: WizardData, options?: { workspaceOrganizationName?: string | null }) {
  const cloudProviders = data.infrastructure.cloudProviders ?? [data.infrastructure.type === 'hybrid' ? 'aws' : data.infrastructure.type === 'self-hosted' ? 'aws' : data.infrastructure.type];
  const usesAws = cloudProviders.includes('aws');
  const usesAzure = cloudProviders.includes('azure');
  const usesGcp = cloudProviders.includes('gcp');
  const usesHybrid = cloudProviders.length > 1 || data.infrastructure.hostsOwnHardware;
  const isSelfHosted = data.infrastructure.hostsOwnHardware && cloudProviders.length === 0;
  const workspaceOrganizationName = options?.workspaceOrganizationName?.trim() || data.company.name;
  const isSameAsCompany = data.company.organizationRelationship === 'same-as-company';
  const governingOrganizationName = isSameAsCompany ? data.company.name : workspaceOrganizationName;

  return {
    organization_name: data.company.name,
    company_name: data.company.name,
    workspace_organization_name: workspaceOrganizationName,
    governing_organization_name: governingOrganizationName,
    governed_company_name: data.company.name,
    company_is_workspace_organization: isSameAsCompany,
    organization_relationship: data.company.organizationRelationship,
    primary_product_name: data.scope.systemName,
    effective_date: new Date().toISOString().slice(0, 10),
    policy_version: 'v0.1-draft',
    approver_name: data.company.primaryContactName,
    executive_sponsor_name: data.company.primaryContactName,
    system_owner_name: data.company.primaryContactName,
    security_contact_email: data.company.primaryContactEmail,
    privacy_contact_email: data.company.primaryContactEmail,
    deployment_model: data.scope.isMultiTenant ? 'multi-tenant SaaS' : 'single-tenant SaaS',
    idp_provider: data.infrastructure.idpProvider,
    cloud_providers: cloudProviders,
    hosts_own_hardware: data.infrastructure.hostsOwnHardware,
    uses_aws: usesAws,
    uses_azure: usesAzure,
    uses_gcp: usesGcp,
    uses_hybrid: usesHybrid,
    is_self_hosted: isSelfHosted,
    uses_availability_zones: data.infrastructure.usesAvailabilityZones,
    uses_cloud_vpn: data.infrastructure.usesCloudVpn,
    has_physical_server_room: data.infrastructure.hasPhysicalServerRoom,
    has_hardware_failover: data.infrastructure.hasHardwareFailover,
    requires_biometric_rack_access: data.infrastructure.requiresBiometricRackAccess,
    tracks_media_destruction: data.infrastructure.tracksMediaDestruction,
    is_multi_tenant: data.scope.isMultiTenant,
    access_review_frequency: 'quarter',
    offboarding_sla_hours: data.operations.terminationSlaHours,
    termination_sla_hours: data.operations.terminationSlaHours,
    onboarding_sla_days: data.operations.onboardingSlaDays,
    triage_sla_minutes: 30,
    has_customer_notification_commitment: true,
    customer_notification_window: '72 hours',
    post_incident_review_window: '1 business day',
    risk_review_frequency: 'quarter',
    recovery_time_objective: '8 hours',
    recovery_point_objective: '4 hours',
    critical_support_hours: 'business hours with severity-based escalation',
    recovery_lead_name: data.company.primaryContactName,
    communications_lead_name: data.company.primaryContactName,
    bcdr_test_frequency: 'annually',
    uses_multi_region: cloudProviders.length > 1 || data.infrastructure.hostsOwnHardware,
    uses_backups: true,
    backup_frequency: 'daily',
    backup_retention_period: '35 days',
    restore_test_frequency: 'quarterly',
    backup_encryption_enabled: true,
    minimum_tls_version: '1.2',
    requires_consent: data.tscSelections.privacy,
    requires_mfa: data.operations.requiresMfa,
    requires_peer_review: data.operations.requiresPeerReview,
    requires_cyber_insurance: data.operations.requiresCyberInsurance,
    dsar_acknowledgement_window: '5 business days',
    vendor_review_frequency: 'annually',
    runs_sast: true,
    runs_dependency_scanning: true,
    has_production_change_reviews: true,
    stores_customer_pii: data.scope.dataTypesHandled.includes('Customer PII'),
    has_subprocessors: data.subservices.length > 0,
    subprocessors: data.subservices.map((subservice) => ({
      name: subservice.name,
      service_description: subservice.description,
      role: subservice.role || subservice.description,
      data_shared: subservice.dataShared || 'Not specified',
      review_cadence: subservice.reviewCadence,
      has_assurance_report: subservice.hasAssuranceReport,
      assurance_report_type: subservice.assuranceReportType,
      control_inclusion: subservice.controlInclusion,
    })),
    data_classifications: data.scope.dataTypesHandled.map((dataType) => ({
      name: dataType,
      description: `${dataType} collected or processed by ${data.scope.systemName}`,
    })),
    has_office_locations: false,
    office_locations: [],
    ticketing_system: data.operations.ticketingSystem,
    version_control_system: data.operations.versionControlSystem,
    vcs_provider: data.operations.vcsProvider,
    hris_provider: data.operations.hrisProvider,
    on_call_tool: data.operations.onCallTool,

    // System Description (DC 200) fields
    system_description: data.scope.systemDescription ?? `${data.scope.systemName}`,
    scope_includes_availability: data.tscSelections.availability,
    scope_includes_confidentiality: data.tscSelections.confidentiality,
    scope_includes_privacy: data.tscSelections.privacy,
    scope_includes_processing_integrity: data.tscSelections.processingIntegrity,

    // Governance fields (CC1.1–CC1.5, CC4.1–CC4.2)
    has_employee_handbook: data.governance.hasEmployeeHandbook,
    has_code_of_conduct: data.governance.hasCodeOfConduct,
    acknowledgement_cadence: data.governance.acknowledgementCadence,
    has_disciplinary_procedures: data.governance.hasDisciplinaryProcedures,
    has_board_or_advisory: data.governance.hasBoardOrAdvisory,
    board_meeting_frequency: data.governance.boardMeetingFrequency,
    has_dedicated_security_officer: data.governance.hasDedicatedSecurityOfficer,
    security_officer_title: data.governance.securityOfficerTitle || 'Security Lead',
    has_org_chart: data.governance.hasOrgChart,
    org_chart_maintenance: data.governance.orgChartMaintenance,
    has_job_descriptions: data.governance.hasJobDescriptions,
    has_internal_audit_program: data.governance.hasInternalAuditProgram,
    internal_audit_frequency: data.governance.internalAuditFrequency,
    has_performance_reviews_linked_to_controls: data.governance.hasPerformanceReviewsLinkedToControls,

    // Training fields (CC1.4)
    security_awareness_training_tool: data.training.securityAwarenessTrainingTool,
    training_cadence: data.training.trainingCadence,
    has_phishing_simulation: data.training.hasPhishingSimulation,
    phishing_simulation_frequency: data.training.phishingSimulationFrequency,
    has_security_bulletin_subscription: data.training.hasSecurityBulletinSubscription,

    // Security tooling fields (CC6.6, CC6.8, CC7.1, A1.1)
    siem_tool: data.securityTooling.siemTool,
    has_siem: !!data.securityTooling.siemTool,
    has_ids_ips: data.securityTooling.hasIdsIps,
    has_waf: data.securityTooling.hasWaf,
    endpoint_protection_tool: data.securityTooling.endpointProtectionTool,
    has_endpoint_protection: !!data.securityTooling.endpointProtectionTool,
    has_mdm: data.securityTooling.hasMdm,
    mdm_tool: data.securityTooling.mdmTool,
    vulnerability_scanning_tool: data.securityTooling.vulnerabilityScanningTool,
    has_vulnerability_scanning: !!data.securityTooling.vulnerabilityScanningTool,
    penetration_test_frequency: data.securityTooling.penetrationTestFrequency,
    has_penetration_testing: data.securityTooling.penetrationTestFrequency !== 'none',
    has_dast: data.securityTooling.hasDast,
    monitoring_tool: data.securityTooling.monitoringTool,
    has_monitoring_tool: !!data.securityTooling.monitoringTool,
    has_autoscaling: data.securityTooling.hasAutoscaling,
    log_retention_days: data.securityTooling.logRetentionDays,

    // Compliance maturity & audit type (drives template tone and audit period language)
    industry: data.company.industry,
    compliance_maturity: data.company.complianceMaturity,
    is_first_timer: data.company.complianceMaturity === 'first-time',
    target_audit_type: data.company.targetAuditType,
    is_type1: data.company.targetAuditType === 'type1',
    is_type2: data.company.targetAuditType === 'type2',
    org_age: data.company.orgAge,

    // Extended operations fields (CC2.2, CC2.3, CC3.2, CC3.3, C1.1, C1.2)
    policy_publication_method: data.operations.policyPublicationMethod,
    has_customer_contracts: data.operations.hasCustomerContracts,
    has_customer_support_channel: data.operations.hasCustomerSupportChannel,
    has_release_note_practice: data.operations.hasReleaseNotePractice,
    has_risk_register: data.operations.hasRiskRegister,
    includes_fraud_risk_in_assessment: data.operations.includesFraudRiskInAssessment,
    has_nda_process: data.operations.hasNdaProcess,
    data_retention_defined: data.operations.dataRetentionDefined,
    has_data_disposal_procedure: data.operations.hasDataDisposalProcedure,
  };
}
